AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: logan-gateway
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
      EndpointConfiguration:
        Type: EDGE
  GetAssignmentFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetAssignment
      Handler: services/backend/src/controllers/assignments-controller.getAssignment
      Role: arn:aws:iam::417995070141:role/LoganLambdaRole
      Runtime: nodejs12.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /assignments/{aid}
            Method: get
            RestApiId:
              Ref: ApiGateway
  GetAssignmentsFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetAssignments
      Handler: services/backend/src/controllers/assignments-controller.getAssignments
      Role: arn:aws:iam::417995070141:role/LoganLambdaRole
      Runtime: nodejs12.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /assignments
            Method: get
            RestApiId:
              Ref: ApiGateway
  CreateAssignmentFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateAssignment
      Handler: services/backend/src/controllers/assignments-controller.createAssignment
      Role: arn:aws:iam::417995070141:role/LoganLambdaRole
      Runtime: nodejs12.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /assignments
            Method: post
            RestApiId:
              Ref: ApiGateway
  UpdateAssignmentFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UpdateAssignment
      Handler: services/backend/src/controllers/assignments-controller.updateAssignment
      Role: arn:aws:iam::417995070141:role/LoganLambdaRole
      Runtime: nodejs12.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /assignments/{aid}
            Method: put
            RestApiId:
              Ref: ApiGateway
  DeleteAssignmentFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/backend/src/controllers/assignments-controller.deleteAssignment
      Role: arn:aws:iam::417995070141:role/LoganLambdaRole
      FunctionName: DeleteAssignment
      Runtime: nodejs12.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /assignments/{aid}
            Method: delete
            RestApiId:
              Ref: ApiGateway
  GetCourseFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetCourse
      Handler: services/backend/src/controllers/courses-controller.getCourse
      Role: arn:aws:iam::417995070141:role/LoganLambdaRole
      Runtime: nodejs12.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /courses/{cid}
            Method: get
            RestApiId:
              Ref: ApiGateway
  GetCoursesFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetCourses
      Handler: services/backend/src/controllers/courses-controller.getCourses
      Role: arn:aws:iam::417995070141:role/LoganLambdaRole
      Runtime: nodejs12.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /courses
            Method: get
            RestApiId:
              Ref: ApiGateway
  CreateCourseFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateCourse
      Handler: services/backend/src/controllers/courses-controller.createCourse
      Role: arn:aws:iam::417995070141:role/LoganLambdaRole
      Runtime: nodejs12.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /courses
            Method: post
            RestApiId:
              Ref: ApiGateway
  UpdateCourseFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UpdateCourse
      Handler: services/backend/src/controllers/courses-controller.updateCourse
      Role: arn:aws:iam::417995070141:role/LoganLambdaRole
      Runtime: nodejs12.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /courses/{cid}
            Method: put
            RestApiId:
              Ref: ApiGateway
  DeleteCourseFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/backend/src/controllers/courses-controller.deleteCourse
      Role: arn:aws:iam::417995070141:role/LoganLambdaRole
      FunctionName: DeleteCourse
      Runtime: nodejs12.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /courses/{cid}
            Method: delete
            RestApiId:
              Ref: ApiGateway
