branch-defaults:
  default:
    environment: logan-backend-dev
    group_suffix: null
deploy:
  artifact: backend.zip
global:
  application_name: logan-backend
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 12
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
