name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      deploy-infra:
        description: Deploy infra
        type: boolean
        required: true
      deploy-frontend:
        description: Deploy frontend
        type: boolean
        required: true
      deploy-backend:
        description: Deploy frontend
        type: boolean
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  pull-requests: write
  actions: read

env:
  GHA_WORKER_ROLE: arn:aws:iam::970547354432:role/gha-worker

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      deploy-infra: ${{ steps.changed-paths.outputs.infra }}
      deploy-frontend: ${{ steps.changed-paths.outputs.frontend }}
      deploy-backend: ${{ steps.changed-paths.outputs.backend }}
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Determine changed paths
        if: ${{ github.event_name == 'push' }}
        uses: dorny/paths-filter@v3
        id: changed-paths
        with:
          filters: |
            infra:
              - 'infra/**'
              - '.github/workflows/deploy.yml'
              - '.github/workflows/terraform.yml'
            frontend:
              - 'services/frontend/**'
              - 'packages/fe-shared/**'
              - 'scripts/deploy-frontend.sh'
              - '.github/workflows/deploy.yml'
            backend:
              - 'services/backend/**'
              - 'packages/aws/**'
              - 'packages/core/**'
              - 'scripts/deploy-backend.sh'
              - 'scripts/copy-be-dependencies.sh'
              - '.github/workflows/deploy.yml'

  deploy-infra:
    needs: setup
    if: ${{ inputs.deploy-infra || needs.setup.outputs.deploy-infra == 'true' }}
    uses: ./.github/workflows/terraform.yml
    with:
      apply: true
    secrets: inherit

  deploy-frontend:
    needs: setup
    if: ${{ inputs.deploy-frontend || needs.setup.outputs.deploy-frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.GHA_WORKER_ROLE }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-west-2
      -
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      -
        name: Install dependencies
        run: |
          npm ci
      -
        name: npm build
        run: npm run build
        working-directory: ./services/frontend
      -
        name: Upload to S3
        run: |
          aws s3 sync public s3://logan-frontend/ --delete --acl public-read
        working-directory: ./services/frontend
  
  deploy-backend:
    needs: setup
    if: ${{ inputs.deploy-backend || needs.setup.outputs.deploy-backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.GHA_WORKER_ROLE }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-west-2
      -
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      -
        name: Install dependencies
        run: |
          npm ci
      -
        name: sam build
        run: sam build
      -
        name: sam deploy
        run: sam deploy
