name: Deploy Backend

on:
  push:
    branches-ignore:
      - '!master' # Ignore all branches other than master
    paths:
      - '!**/node_modules/**'
      - 'scripts/copy-be-dependencies.js'
      - 'packages/aws/**'
      - 'packages/core/**'
      - 'services/backend/**'
jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Lerna & Bootstrap
        run: |
          npm ci
          npm run bootstrap:backend
      - name: Copy local dependencies to node_modules
        run: node scripts/copy-be-dependencies.js
      - name: Create artifact
        run: npm run bundle
        working-directory: services/backend
      - name: Deploy
        uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          command: deploy logan-backend-dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.EB_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.EB_ACCESS_KEY_SECRET }}
          AWS_DEFAULT_REGION: 'us-west-2'
