name: Linting and Tests

on: pull_request

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies & bootstrap
        run: |
          npm ci
          npm run bootstrap
      - name: Run lint check
        run: npm run lint
      - name: Run tests
        run: npm run test
