name: lint-and-test-node

on:
  workflow_call:

permissions:
  contents: read

jobs:

  lint-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      -
        name: Install dependencies
        run: |
          npm ci
      -
        name: Run lint check
        run: npm run lint
      -
        name: Run tests
        run: npm run test
