name: pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      node-changes: ${{ steps.changed-paths.outputs.node == 'true' }}
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Determine changed paths
        if: ${{ github.event_name == 'push' }}
        uses: dorny/paths-filter@v3
        id: changed-paths
        with:
          filters: |
            node:
              - '.github/workflows/lint-and-test-node.yml'
              - 'services/**'
              - 'packages/**'
              - 'package.json'
              - 'package-lock.json'
              - 'lerna.json'
              - '**.js'

  lint-and-test-node:
    needs: setup
    if: needs.setup.outputs.node-changes
    uses: ./.github/workflows/lint-and-test-node.yml

  pr-ready:
    if: always()
    needs:
      - setup
      - lint-and-test-node
    runs-on: ubuntu-latest
    steps:
      -
        name: Validate jobs
        if: ${{ contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
        run: |
          echo "::error title=${{ github.workflow }}::at least one job failed or cancelled"
          exit 1
