name: pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      infra-changes: ${{ steps.changed-paths.outputs.infra }}
      node-changes: ${{ steps.changed-paths.outputs.node == 'true' }}
    steps:
      -
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Determine changed paths
        uses: dorny/paths-filter@v3
        id: changed-paths
        with:
          filters: |
            infra:
              - '.github/workflows/terraform.yml'
              - 'infra/**'
            node:
              - '.github/workflows/lint-and-test-node.yml'
              - 'services/**'
              - 'packages/**'
              - 'package.json'
              - 'package-lock.json'
              - '**.js'

  terraform-plan:
    needs: setup
    if: ${{ needs.setup.outputs.infra-changes == 'true' }}
    uses: ./.github/workflows/terraform.yml

  lint-and-test-node:
    needs: setup
    if: ${{ needs.setup.outputs.node-changes }}
    uses: ./.github/workflows/lint-and-test-node.yml

  pr-ready:
    if: always()
    needs:
      - setup
      - lint-and-test-node
      - terraform-plan
    runs-on: ubuntu-latest
    steps:
      -
        name: Validate jobs
        if: ${{ contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
        run: |
          echo "::error title=${{ github.workflow }}::at least one job failed or cancelled"
          exit 1
