name: pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      infra-changes: ${{ steps.changed-paths.outputs.infra }}
      node-changes: ${{ steps.changed-paths.outputs.node }}
    steps:
      -
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Determine changed paths
        uses: dorny/paths-filter@v3
        id: changed-paths
        with:
          filters: |
            infra:
              - '.github/workflows/terraform.yml'
              - 'infra/**'
            node:
              - '.github/workflows/linting-and-tests.yml'
              - 'services/**'
              - 'packages/**'
              - 'package.json'
              - 'package-lock.json'
              - '**.js'
            frontend:
              - 'packages/**'
              - 'services/frontend/**'

  linting-and-tests:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.node-changes == 'true' }}
    uses: ./.github/workflows/linting-and-tests.yml
    secrets: inherit

  validate-frontend-build:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.node-changes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      -
        name: Install dependencies
        run: |
          npm ci
      -
        name: Build frontend
        run: |
          npm -w services/frontend \
            run build

  terraform-plan:
    needs: setup
    if: ${{ needs.detect-changes.outputs.infra-changes == 'true' }}
    uses: ./.github/workflows/terraform.yml

  pr-ready:
    if: always()
    needs:
      - detect-changes
      - linting-and-tests
      - validate-frontend-build
      - terraform-plan
    runs-on: ubuntu-latest
    steps:
      -
        name: Validate jobs
        if: ${{ contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
        run: |
          echo "::error title=${{ github.workflow }}::at least one job failed or cancelled"
          exit 1
