name: pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      node-changes: ${{ steps.changed-paths.outputs.node }}
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Determine changed paths
        uses: dorny/paths-filter@v3
        id: changed-paths
        with:
          filters: |
            node:
              - '.github/workflows/lint-and-test-node.yml'
              - 'services/**'
              - 'packages/**'
              - 'package.json'
              - 'package-lock.json'
              - '**.js'

  linting-and-tests:
    needs: setup
    if: ${{ needs.setup.outputs.node-changes == 'true' }}
    uses: ./.github/workflows/linting-and-tests.yml

  pr-ready:
    if: always()
    needs:
      - setup
      - linting-and-tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Validate jobs
        if: ${{ contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
        run: |
          echo "::error title=${{ github.workflow }}::at least one job failed or cancelled"
          exit 1
