name: terraform

on:
  workflow_call:
    inputs:
      apply:
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write
  pull-requests: write
  actions: read

defaults:
  run:
    shell: bash

env:
  TERRAFORM_VERSION: 1.10.3
  GHA_WORKER_ROLE: arn:aws:iam::970547354432:role/gha-worker

jobs:

  plan:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.GHA_WORKER_ROLE }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-west-2
      -
        name: terraform init
        run: terraform init
        working-directory: infra
      -
        name: terraform plan
        id: plan
        working-directory: infra
        run: |
          # Wrapping to capture logs and exit status
          (
            set +e
            terraform plan;
            echo "$?" > "${{ runner.temp }}/plan-status.txt";
          ) 2>&1 | tee "${{ runner.temp }}/plan-output.txt"

          exit_code=$(cat "${{ runner.temp }}/plan-status.txt")
          echo "exit_code=$exit_code" | tee -a "$GITHUB_OUTPUT"
          
          exit "$exit_code"
      -
        name: Capture plan logs
        id: plan-logs
        if: ${{ !cancelled() }}
        run: |
          stopToken=$(date '+%s')
          echo "::stop-commands::${stopToken}"
          {
            echo 'logs<<EOF';
            cat "${{ runner.temp }}/plan-output.txt";
            echo 'EOF';
          } | tee -a "$GITHUB_OUTPUT"
          echo "::${stopToken}::"
      -
        name: Comment plan result
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ !cancelled() }}
        with:
          recreate: true
          header: terraform-plan
          message: |
            `terraform plan` ${{ steps.plan.outputs.exit_code == '0' && 'succeeded' || 'failed' }}

            <details>
              <summary>plan result</summary>

              ```
              ${{ steps.plan-logs.outputs.logs }}
              ```
            </details>


  apply:
    needs: plan
    if: ${{ inputs.apply == true }}
    environment: infra-prod
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.GHA_WORKER_ROLE }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-west-2
      -
        name: terraform init
        run: terraform init
        working-directory: infra
      -
        name: terraform apply
        working-directory: infra
        run: |
          terraform apply \
            -auto-approve
